version: "3.9"

services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Taktalifum123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"
      healthcheck:
        test: [ "CMD", "redis-cli", "ping" ]
        interval: 5s
        timeout: 3s
        retries: 10

  payment-service:
    build: ./payment-service
    environment:
      DATABASE_URL: postgres://postgres:Taktalifum123@postgres:5432/payment_db?sslmode=disable
      GRPC_ADDR: :9091
      HTTP_ADDR: :8081
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8081:8081"
      - "9091:9091"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  order-service:
    build: ./order-service
    environment:
      DATABASE_URL: postgres://postgres:Taktalifum123@postgres:5432/order_db?sslmode=disable
      PAYMENT_GRPC_ADDR: payment-service:9091
      HTTP_ADDR: :8080
      ORDER_GRPC_ADDR: :9090
      REDIS_ADDR: redis:6379
      CACHE_TTL_SECONDS: 300
      RATE_LIMIT_REQUESTS: 10
      RATE_LIMIT_WINDOW_SECONDS: 60
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
      payment-service:
        condition: service_started
      redis:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672/
      REDIS_ADDR: redis:6379
      PROVIDER_MODE: SIMULATED
      MAX_RETRIES: 3
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata: